# Generated by Django 5.1.3 on 2024-12-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_remove_publication_category_edition_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('authors', models.CharField(max_length=500, verbose_name='Авторы')),
                ('source', models.CharField(max_length=500, verbose_name='Источник')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('url', models.URLField(blank=True, verbose_name='URL-адрес')),
            ],
            options={
                'verbose_name': 'внешний источник',
                'verbose_name_plural': 'Внешние источники',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='external_citations',
            field=models.ManyToManyField(blank=True, related_name='cited_by', to='publications.externalpublication', verbose_name='Внешние источники'),
        ),
    ]
